#include "header.h"

int sum = 0; 

// sum has been declared as an integer

void secret()
{
    int local_seed = (int)time(NULL);
    seed = local_seed;
    sum = 0;
	while (local_seed>0)
	{
	    int temp = local_seed % 10;
		local_seed /= 10;
        sum += temp;
	}

    /*
    The algorithm in the secret() function has been modified to use the sum of the digits of the time(seconds) elapsed since 
    00:00:00 hours, GMT (Greenwich Mean Time), January 1, 1970. (Number will change with each run)
    instead of a randomly generated value. This prevents the sum variable from taking in a large value and encountering an integer
    overflow since this sum of digits will never exceed INT_MAX. 
    */
}


int parabola(int c)
{
    double x = sqrt(4*sum*c);
    return (int)x;

    /*
    Since the value generated by sum is always a positive value lesser than INT_MAX, the previous issues have been removed
    and the sqrt() function no longer returns zero. Hence the encryption distance is always a positive value and all the 
    characters in the original string get encrypted.
    */
}

void encrypt(char *str,char *enstr)
{
    secret();
    int l = strlen(str);
    int i = 0;
    while(i<l)
    {
        if(str[i]!=' ')
            enstr[i] = (str[i] + parabola(i));
        else
            enstr[i] = ' ';
        i++;
    }
    enstr[i] = '\0';    // '\0' delimiter has been appended at the end of the encrypted string
}

int inv_parabola(int c)
{
    double x = -1*sqrt(4*sum*c);
    return (int)x;

    /*
    Since the value generated by sum is always a positive value lesser than INT_MAX, the previous issues have been removed
    and the sqrt() function no longer returns zero. Hence the decryption distance is always a positive value and all the 
    characters in the original string get decrypted.
    */
}

void decrypt()
{
    char destr[100000];
    char temp[100000];
    int i = 0;          // Unused variable c has been removed

    FILE *fp = fopen("Encrypted.txt","r");
    
    if(fp==NULL)        // A check has been added to ensure the file exists and terminate if it does not return NULL
    {
        printf("File problem,exiting.\n");
        exit(0);
    }
    
    while(1)
    {
        if(i==0)
        {
            fscanf(fp,"%s\n",temp);
            sum = atoi(temp);
            printf("Key: %d\n",sum);
            i++;
            continue;
        }
        else
        {
            fscanf(fp,"%[^\n]s",temp);
            int l = strlen(temp);
            int j = 0;
            while(j<l)
            {
                if(temp[j]==' ')
                    destr[j] = ' ';
                else if(temp[j]=='\n')
                    destr[j] = '\n';
                else
                    destr[j] = (char)((int)temp[j] + inv_parabola(j));
                j++;
            }
            destr[j] = '\0';
        }
        if(feof(fp))
        	break;
    }
    
    fclose(fp);         // fp has been closed after all the file reading operations
    
    printf("The decrypted string is:\n%s\n",destr);

    //The two free statements to static functions have been removed
}

void write_to_file(char*s)
{
    FILE* fp = fopen("Encrypted.txt","w");
    fprintf(fp,"%d\n%s",sum,s);
    fclose(fp);
}
